    // Google falou que ficaria mais fácil com uma variável 
let resposta = " ";

function verificar() {
    // se não clicar em nada
    if (resposta == " ") {
        resultado.innerText("escolha uma opção primeiro");
    }
    // Corrigido: agora testamos a variável 'resposta'
    else if (resposta == "verdadeiro") {
        resultado.innerText("parabéns!");
    }
    else {
        resultado.innerText("resposta errada");
    }
}